//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azimzadeh_MVC_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int BannerId { get; set; }
        public string Title { get; set; }
        public string LinkUrl { get; set; }
        public string ImagePath { get; set; }
        public string Position { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    }
}
