//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azimzadeh_MVC_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildMenu
    {
        public int ChildMenuId { get; set; }
        public int ParentMenuId { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ParentMenu ParentMenu { get; set; }
    }
}
