//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azimzadeh_MVC_project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public int ProductId { get; set; }
        public int UserId { get; set; }
        public byte Rating { get; set; }
        public string Comment { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
